name: Canary

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:

  Canary:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3

    - run: ./.github/setup.sh

    - run: ./cli/cli.py check
